### PR TITLE
Fix _removeModels regression

### LINKED ISSUE #3693: _removeModels regression bug
It looks like in 1.2.1, _removeModels was simplified, but introduced a regression bug.

```
    _removeModels: function(models, options) {
      var removed = [];
      for (var i = 0; i < models.length; i++) {
        var model = this.get(models[i]);
        if (!model) continue;
        // CODE REMOVED HERE

        var index = this.indexOf(model);
        this.models.splice(index, 1);
        this.length--;

        if (!options.silent) {
          options.index = index;
          model.trigger('remove', model, this, options);
        }

        removed.push(model);
        this._removeReference(model, options);
      }
      return removed.length ? removed : false;
    },
```

Removed the following lines after `if (!model) continue;`

```
        var id = this.modelId(model.attributes);
        if (id != null) delete this._byId[id];
        delete this._byId[model.cid];
```

What this means is that if you are listening to a remove event and you check for removal, you will get into an infinite loop because the event is now called before the id is removed from `this._byId`:

```
    if (current_related_model = collection.get(id)) collection.remove(current_related_model)
```

I think the _byId code should be put back so when events are fired, they represent the most up-to-date state.

### PR DESCRIPTION
**Pull request by jridgewell**
Fixes #3693.

This leaves open the question of whether events triggered on the model
during a ‘remove’ listener should also trigger on the collection. Just
something to revisit for V2.

```js
col.on('other', (model) => {
  // Should this be triggered?
});

col.on('remove', (model) => {
  // If the model is really "removed" (we can't `#get` it anymore)
  // by the time this listener is called, then I'd argue that this
  // shouldn't trigger the 'other' event on the collection...
  model.trigger('other');
});
```

### CODE REVIEW

File: backbone.js [hunk 1]
```diff
@@ -1088,6 +1088,12 @@
         this.models.splice(index, 1);
         this.length--;
 
+        // Remove references before triggering 'remove' event to prevent an
```
Comment (dmitrigrabov) [inline backbone.js]: Does this work?

**Comment by akre54** [comment]
All events maybe not, but a `remove` definitely should.

**Comment by jridgewell** [comment]
I think this warrants a `v1.2.4`?

**Comment by akre54** [comment]
Want to add a test that `col.on('other', ...)` doesn't trigger?

**Comment by jridgewell** [comment]
It's in #3806, but I'm waiting till v2.
